### ISSUE TITLE
Syntax highlighter feature requested 

### ISSUE THREAD

**Issue by ciscohack** [bgw/dotfiles#3]
Hi Team,

First, I would like to say thanks to you all for the amazing work.

Team, I have a feature request, if you people consider in upcoming releases. is it possible for you folks to add syntax highlighter feature for networking devices? like cisco, juniper and other vendors. I am aware SecureCRT/iterm2 tool have such feature where we can build regex-based syntax highlight for keywords for better readability while live troubleshooting.  looking forward to a positive response.

**Comment by bgw** [comment]
Hey, @ciscohack, this is a repository for my own personal system configuration files. If you want to pull things from it, that's great, but I'm not providing any support.

**Comment by ciscohack** [comment]
Oh, my friend, I am sorry seems i put the comment on the wrong place
